"""
에러 코드 정의

서비스 계층이 반환하는 응답의 `error_code` 필드에 사용된다.
핸들러는 이 코드로 분기해 사용자 메시지를 결정한다.
"""


class ErrorCode:
    """표준화된 에러 코드"""

    USER_NOT_FOUND = "USER_NOT_FOUND"
    MARKET_CLOSED = "MARKET_CLOSED"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    INSUFFICIENT_CASH = "INSUFFICIENT_CASH"
    INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK"
    STOCK_NOT_FOUND = "STOCK_NOT_FOUND"
    PRICE_UNAVAILABLE = "PRICE_UNAVAILABLE"
    NOT_FOUND = "NOT_FOUND"
    INVALID_INPUT = "INVALID_INPUT"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    INVALID_AMOUNT = "INVALID_AMOUNT"
    INVALID_BET = "INVALID_BET"
    INVALID_CHOICE = "INVALID_CHOICE"
    INVALID_PARAMETER = "INVALID_PARAMETER"
    INVALID_STATE = "INVALID_STATE"
    DAILY_LIMIT_REACHED = "DAILY_LIMIT_REACHED"
    DUPLICATE_ACTION = "DUPLICATE_ACTION"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    UNAUTHORIZED = "UNAUTHORIZED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    DB_ERROR = "DB_ERROR"
    API_ERROR = "API_ERROR"
    TIMEOUT = "TIMEOUT"
